file:
  location: /tmp

server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: 1234

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  datasource:
    url: jdbc:mysql://141.164.41.213:3306/okky_db?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kimcoding
    password: dkwmfrjdns1!
    platform: mariadb

    jpa:
      hibernate:
        ddl-auto: create-drop
        use-new-id-generator-mappings: false
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
      generate-ddl: true

logging:
  level:
    root: warn
    com.simple.portal: error