file:
  location: /tmp

server:
  port: 8081

spring:
  security:
    user:
      name: admin
      password: 1234

  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB

  freemarker:
    check-template-location: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: xowns4817@gmail.com
    password: password
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
              enable: true
        mime:
            charset: UTF-8
            transport:
              protocol: smtp
    default-encoding: UTF-8

  datasource:
    url: ENC(p96dBiARC6AkxQGtZL925cCut/Np7JwsbExtga5IoffyhPQE9DvftPafH6yeAupbycasUvp9g8sqpfRpEQvgyzc8Pgw/A4fNwLezl/SDqVfY+H8IkAVVnpth+Fmz3leq)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(Bev9/LnXQMnYBO5rLKbHgRjRzYSymiuy)
    password: ENC(1SOP0D2SCzUmMfYkfw1BrwWiKeX+v7a8)
    platform: mariadb

    jpa:
      hibernate:
        ddl-auto: none
        use-new-id-generator-mappings: false
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: false
      properties:
        hibernate:
          format_sql: true
      generate-ddl: false
  profile:
    value: dev

logging:
  level:
    root: warn
    #com.simple.portal: error
    com.simple.portal: debug

